---
title: "Sankey diagrams and how to create"
subtitle: "NSC-R Tidy Tuesday March 2022"
author: Tim Verlaan
date: "2022-03-09"
format:
    html 
---

## Introduction

In this meeting, Tim Verlaan explains what Sankey diagrams are, and how they can be created in R [@verlaan_nsc-rn_2022]

## Get started

```{r}
#| warning: false
#| echo: true
library(tidyr)
library(dplyr)
library(readr)

```

```{r}
#| warning: false
#| echo: true
relig_income
```

```{r}
#| warning: false
#| echo: true
?pivot_longer

```

```{r}
#| warning: false
#| echo: true
pivot_longer(relig_income, !religion)
```

```{r}
#| warning: false
#| echo: true
df <- relig_income |>
  pivot_longer(!religion, names_to = 'income', values_to = 'count')
```

```{r}
#| warning: false
#| echo: true
billboard

```

```{r}
#| warning: false
#| echo: true
billboard |>
  pivot_longer(
    cols = starts_with('wk'),
    values_drop_na = TRUE,
    names_to = "week",
    values_to = 'rank',
    names_prefix = "wk",
    names_transform = list(week = as.integer)
  )
```

```{r}
#| warning: false
#| echo: true
#install.packages("remotes")
#remotes::install_github("davidsjoberg/ggsankey")
library(ggsankey)
library(ggplot2)
```

```{r}
#| warning: false
#| echo: true
?mtcars

df <- mtcars |>
  make_long(cyl, vs, am, gear, carb)
```

```{r}
#| warning: false
#| echo: true
#| label: Sankey
#| fig-cap: "Sankey graph"
#| cap-location: margin
ggplot(df, aes(x = x,
               node = node,
               next_x = next_x,
               next_node = next_node,
               fill = factor(node),
               label = node)) +
  geom_sankey() +
  geom_sankey_label() 
```

```{r}
df1 <- mtcars |>
  select(cyl, vs, am, gear, carb) |>
  pivot_longer(everything()) |>
  mutate(next_x = lead(.data$name),
         next_node = lead(.data$value)
  )
```

# References
