project:
  type: book

book:
  title: "TT_book"
  author: "Wim Bernasco, Asier Moreva, Sam Langton, Alex Trinidad, Francisca Yasselbi-de Kom, Tim Verlaan, Harrie Jonkman"
  date: "2-2-2023"
  chapters:
    - index.qmd
    - intro.qmd
    - 01_TT_202201.qmd
    - 02_TT_202202.qmd
    - 03_TT_202202.qmd
    - 05_TT_202203.qmd
    - 06_TT_202204.qmd
    - 08_TT_202205.qmd
    - 10_TT_202211.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

