project:
  type: book
  output-dir: _book

book:
  title: "TT_book"

  page-footer:
    left: |
      Wim Bernasco, Asier Moreva, Sam Langton,
      Alex Trinidad, Francisca Yasreli-de Kom,
      Tim Verlaan & Harrie Jonkman.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/Screenshot.png
  favicon: cover.png
  site-url: https://ttbook.netlify.app
  repo-url: https://github.com/Jonkman1/TT_book
  repo-branch: main
  date: "2-2-2023"
  chapters:
    - index.qmd
    - 00_intro.qmd
    - 01_TT_202201.qmd
    - 02_TT_202202.qmd
    - 03_TT_202202.qmd
    - 04_TT_202203.qmd
    - 05_TT_202203.qmd
    - 06_TT_202204.qmd
    - 07_TT_202205.qmd
    - 08_TT_202205.qmd
    - 09_TT_202211.qmd
    - 10_TT_202301.qmd
    - 11_summary.qmd
    - references.qmd

bibliography: referencestt.bib
csl: apa.csl

format:
   html:
    theme:
      - cosmo
    code-link: true


editor: visual

